#Basic makefile for compiling our application.

# -g Makes debug info available for tools like gdb.
# -Wall will make the compiler throw warnings for all things it can throw warnings for.
CFLAGS = -g -Wall

build:
	gcc main.c $(CFLAGS) -o main.o
